// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR734gxDlp5VOexRcqFmMyQccjbKXHTWU',
    appId: '1:689367854598:web:dbfdb39b3efa1a57059d87',
    messagingSenderId: '689367854598',
    projectId: 'bookshop-d9283',
    authDomain: 'bookshop-d9283.firebaseapp.com',
    storageBucket: 'bookshop-d9283.firebasestorage.app',
    measurementId: 'G-TEEGBE0ER4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7NWktXyS-dYYqQOkdJK_KtjhZtH_HKVo',
    appId: '1:689367854598:android:2458356309fdfd19059d87',
    messagingSenderId: '689367854598',
    projectId: 'bookshop-d9283',
    storageBucket: 'bookshop-d9283.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf0lFbiTMr7EqiAqmJX0iuJxNmWvNtwb8',
    appId: '1:689367854598:ios:e7688172186621d8059d87',
    messagingSenderId: '689367854598',
    projectId: 'bookshop-d9283',
    storageBucket: 'bookshop-d9283.firebasestorage.app',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf0lFbiTMr7EqiAqmJX0iuJxNmWvNtwb8',
    appId: '1:689367854598:ios:e7688172186621d8059d87',
    messagingSenderId: '689367854598',
    projectId: 'bookshop-d9283',
    storageBucket: 'bookshop-d9283.firebasestorage.app',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR734gxDlp5VOexRcqFmMyQccjbKXHTWU',
    appId: '1:689367854598:web:9c3a7860113323ac059d87',
    messagingSenderId: '689367854598',
    projectId: 'bookshop-d9283',
    authDomain: 'bookshop-d9283.firebaseapp.com',
    storageBucket: 'bookshop-d9283.firebasestorage.app',
    measurementId: 'G-398KFXN3R2',
  );

}